title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

twitter_username: jekyllrb
github_username:  jekyll

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
prose:
  rooturl: '_posts'
  metadata:
    _posts:
      - name: "published"
        field:
          element: "hidden"
          value: "true"
      - name: "title"
        field:
          element: "text"
          label: "Заголовок"
          value: ""
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "category"
        field:
          element: "select"
          label: "Выбрать категорию"
          placeholder: "Выбрать категорию"
          options:
            - name: "Введение"
              value: "vvedenie"
            - name: "Основная"
              value: "osnovnaya"
            - name: "Заключительная"
              value: "zakluchitelnaya"
            - name: "Вспомогательные материалы"
              value: "vspomogatelnye materialy"
